services:
  node-a:
    build: .
    container_name: p2p-node-a
    privileged: true
    ports:
      - "6080:80"        # noVNC Web UI for Node A
      - "9000:9000"      # TCP Port
      - "9001:9001/udp"  # QUIC Port
    volumes:
      - .:/root/Desktop/raw_mini
    cap_add:
      - NET_ADMIN
    networks:
      p2p_net:
        ipv4_address: 172.20.0.10

  node-b:
    build: .
    container_name: p2p-node-b
    privileged: true
    ports:
      - "6081:80"        # noVNC Web UI for Node B
    volumes:
      - .:/root/Desktop/raw_mini
    cap_add:
      - NET_ADMIN
    networks:
      p2p_net:
        ipv4_address: 172.20.0.11

networks:
  p2p_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
